###
GET http://localhost:3000/contacts


###
GET http://localhost:3000/contacts/626d4fee6c541ee99a3508ad

###
GET http://localhost:3000/contacts/626d4fee6c541ee99a3508ad


###
GET http://localhost:3000/contacts/626d4fee6c541ee99a3508af

###
//Deployment

GET https://personal-test2.herokuapp.com/contacts/626d4fee6c541ee99a3508ad

###
GET https://personal-test2.herokuapp.com/contacts/626d4fee6c541ee99a3508ad

###
GET https://personal-test2.herokuapp.com/contacts/626d4fee6c541ee99a3508af